---
title: "Function plots"
output: html_notebook
---
```{r}
#libraries
library(ggplot2)
```


```{r}
# data for curves
x <- data.frame(x = c(-4,4))
```


```{r}
# normal distribution curve
ggplot(data = x)+
  stat_function(mapping = aes(x =x ),fun = dnorm)
```

```{r}
# t-distributions
ggplot(data = x) +
  stat_function(mapping = aes(x = x),
                fun = dt, 
                args = list(df = 1),
                color = "red") +
  stat_function(mapping = aes(x = x),
                fun = dt,
                args = list(df = 5),
                color = "green") +
  stat_function(mapping = aes(x = x),
                fun = dt,
                args = list(df = 20),
                color = "blue") +
  stat_function(mapping = aes(x = x),
                fun = dnorm)

```

```{r}
# adding points to the x axis of a normal distribution
df <- data.frame(c(-0.5, 0.5), c(0,0))
colnames(df) <- c("x", "y")
ggplot(data = x) +
  stat_function(mapping = aes(x = x),
                fun = dnorm) +
  geom_point(data = df,
            mapping = aes(x = x, y =y)) +
  stat_function(fun = dnorm,
                geom = "area",
                fill = "steelblue",
                xlim = c(-0.5, 0.5))
  
```

