---
title: "R Notebook"
output: html_notebook
---


```{r, echo=FALSE}
packages <- c(
  'ggplot2',
  'ggrepel',
  'patchwork',
  'ggraph',
  'dplyr',
  'gganimate',
  'gifski',
  'ggforce',
  'ggthemes',
  'maps',
  'sf',
  'tidyr',
  'concaveman',
  'remotes'
)

#install.packages(packages)

library(tidyverse)
library(ggplot2)
```
```{r}
data("faithful")
ggplot(data = faithful, mapping = aes(x = eruptions, y = waiting)) +
  geom_point()
```
```{r}
data("faithful")
ggplot(data = faithful) +
  geom_point(mapping = aes(x = eruptions,
                           y = waiting,
                           colour = eruptions < 3)) # mapping color
```
```{r}
ggplot(data = faithful) +
  geom_point(mapping = aes(x = eruptions,
                           y = waiting),
                           color = "steelblue") # Setting color, notice that color is outside the aes function.
# There is no legend because there is no mapping.
```
```{r}
ggplot(data = faithful, mapping = aes(x = eruptions, y = waiting)) +
  geom_density2d() +
  geom_point()
```
```{r}
ggplot(data = faithful, mapping = aes(x = eruptions, y = waiting)) +
  geom_point() +
  geom_density_2d()
# What is the difference between this plot and the previous one? 
```
```{r}
line_data <- lm(waiting ~ eruptions, data = faithful)
ggplot(data = faithful, mapping = aes(x = eruptions, y = waiting)) +
  geom_point() + 
  geom_abline(slope = line_data$coefficients[2], intercept = line_data$coefficients[1], color = "red" )
```


```{r}
data(mtcar)
ggplot(data = mtcars) +
  geom_point(mapping = aes(x = hp, 
                           y = mpg,
                           colour =factor(cyl),
                           shape = factor(cyl)),
             size = 3.0,
             alpha = 0.5 )
```
```{r r-plot}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy),
             color = "red") +
  geom_point(mapping = aes(x = displ, y = cty),
             color = "blue",
             alpha = 0.2)
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
```
```{r}
two_seater <- mpg %>%
  filter(class == "2seater")
all_except_two_seater <- mpg %>%
  filter(class != "2seater")
```

```{r}
ggplot() +
  geom_point(data = all_except_two_seater, mapping = aes(x = displ, y = hwy)) +
  geom_point(data = two_seater, mapping = aes(x = displ, y = hwy),
             color = "red",
             size = 2.0)
```


